### ISSUE TITLE
How to do stress test for nbase

### ISSUE THREAD

**Issue by Tiaoyu** [naver/nbase-arc#127]
I want to know how much progress there is (nbasev1.2.5  -> nbasev1.4.0) ，but i cannot do a test（stress test or performance tests） use “arc-cli-*”，so i ask this question for your help，could you please help me？

**Comment by sanitysoon** [comment]
You can think a nbase-arc cluster as a big redis server.
Any redis client will work with limited [command set](doc/supported-commands-3.2.9.md)

**Comment by Tiaoyu** [comment]
got it, thank you very much.
