### ISSUE TITLE
Is 1.5.0 version of Java-client available in maven?

### ISSUE THREAD

**Issue by PBW99** [naver/nbase-arc#137]
Is 1.5.0 version of Java-client available?
I followed the instructions in ["Readme.md"](https://github.com/naver/nbase-arc/tree/master/api/java)  
And It says to use version 1.5.0.  
 However, version 1.5.0 did not exist at "mavenrepository.com", and an error appeared during the installation process.  
Is this a mistake in this process or is there no 1.5.0 version?
```c
<dependencies>
    <dependency>
        <groupId>com.navercorp</groupId>
        <artifactId>nbase-arc-java-client</artifactId>
        <version>1.5.0</version>
    </dependency>
</dependencies>
```

![default](https://user-images.githubusercontent.com/22186124/33474694-09659130-d6bf-11e7-892d-9e32b41fc984.png)

![default](https://user-images.githubusercontent.com/22186124/33474698-0e5f43f2-d6bf-11e7-9ed1-2f7481b06bd9.png)

**Comment by otheng03** [comment]
1.5.4 version of java client is available now.
Please use 1.5.4 instead of 1.5.0 because some bugs are fixed in 1.5.4.
Thank you.

![image](https://user-images.githubusercontent.com/5895507/33587392-5126ea42-d9b1-11e7-9d08-71e59cc5c6d5.png)
