### ISSUE TITLE
[solved]cluster create error because of '<version>'

### ISSUE THREAD

**Issue by KOOJANGHOI** [naver/nbase-arc#141]
when I try to create cluster. there were problem about version

<img width="729" alt="2017-12-05 7 39 53" src="https://user-images.githubusercontent.com/26297308/33604019-e26cc90e-d9f7-11e7-94c1-df1c41c8045f.png">

but this error is solved by correcting version in these files
- nbase-arc/confmaster/confmaster-{version}
- nbase-arc/bin/*-{version}
- nbase-arc/mgmt/config/conf_dnode.py
  - REDIS_VERSION = "{version}"
  - GW_VERSION = "{version}"
  - SMR_VERSION = "{version}"

It is like below picture

<img width="640" alt="2017-12-05 8 18 48" src="https://user-images.githubusercontent.com/26297308/33604571-cfbc2226-d9f9-11e7-93b5-80304240232e.png">

And cluster can be created

<img width="740" alt="2017-12-05 7 42 27" src="https://user-images.githubusercontent.com/26297308/33604717-5ac78aa4-d9fa-11e7-96c6-d33d81a59a89.png">

**Comment by otheng03** [comment]
Thank you.

To reduce trial and error, please read guides in https://github.com/naver/nbase-arc/blob/master/doc

Especially, 
https://github.com/naver/nbase-arc/blob/master/doc/admin/SetupGuide.md
![image](https://user-images.githubusercontent.com/5895507/33640730-a1a0751e-da75-11e7-88a2-5a485ccc1a1f.png)
