### ISSUE TITLE
Make listen address configurable for local_proxy

### ISSUE THREAD

**Issue by ogibayashi** [naver/nbase-arc#174]
Hello. I think it would be great if local_proxy supports configuring listen address which is now fixed to the value `INADDR_ANY`.
The reason is that we want to restrict access to the local proxy only from the `localhost` for security reason. Since local_proxy does not have any authentication, it could be dangerous to accept requests from any client. 
What do you think?

**Comment by sanitysoon** [comment]
Thanks for your suggestion.
We will provide command line option that when specified, local proxy will only accept connection request from the specified interfaces.

**Comment by sanitysoon** [comment]
@ogibayashi  We added below configuration directive support.
```
# By default, local proxy listens and accepts for connections from all the network interfaces.
# When bind directive is specified, only connections from the given interface will be served.
# Value must be IPv4 numbers-and-dots notation.
#
# bind 127.0.0.1
```

**Comment by ogibayashi** [comment]
@sanitysoon It worked as expected. Thanks a lot!
