### ISSUE TITLE
after restart server how i cat start services?

### ISSUE THREAD

**Issue by drawhan** [naver/nbase-arc#73]
i install nbase-arc to centos7 and everything is fine

but i reboot linux and i don`t know start service

i search document and there is no manual for system restart

**Comment by otheng03** [comment]
It isn't a normal operational scenario that you reboot a machine with running nbase-arc processes.
Therefore we don't have any manual for it.

For restoration, follow below steps.
```
1. start ZooKeeper
2. start ConfMaster
3. start redis-gateway
4. recover PGS
  4.1. run mgmt script
  4.2. execute "13. Repair Cluster (Cluster already installed)"
```

**Comment by drawhan** [comment]
thank you for your answer

how i can [3. start redis-gateway] ? 

i search manual... but hard to find that

**Comment by otheng03** [comment]
* Gateway execution command
  * ```redis-gateway-<version> -D -l gwlog -c <cm_ip> -b <cm_port> -w <the number of workers> -p <gw_port> -n <cluster_name> -d```
  * Example: ```redis-gateway-v1.3.0 -D -l gwlog -c 127.0.0.1 -b 1122 -w 16 -p 6000 -n test -d```

**Comment by drawhan** [comment]
thanks
