### ISSUE TITLE
cluster create error

### ISSUE THREAD

**Issue by drawhan** [naver/nbase-arc#77]
# system : centos 7.1 x64 / Linux redis1 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
# fab main
#4 cluster create

Cluster name :  cluster
PG count :  4
Replication number :  2
PGS Physical Machine list([["PM_NAME PM_IP", "PM_NAME PM_IP"], ["PM_NAME PM_IP", "PM_NAME PM_IP"], ...]) [["redis1 10.0.0.151", "redis2 10.0.0.152"]]
Gateway Physical Machine list([PM_NAME PM_IP, PM_NAME PM_IP, ...]) ["redis1 10.0.0.151", "redis2 10.0.0.152"]
Cronsave number 2
[user@10.0.0.151] Executing task 'get_ports'

[user@10.0.0.151] Get using ports
[user@10.0.0.151] Login password for 'user': 
[user@10.0.0.152] Executing task 'get_ports'

[user@10.0.0.152] Get using ports
[user@10.0.0.151] Executing task 'get_ports'

[user@10.0.0.151] Get using ports
[user@10.0.0.152] Executing task 'get_ports'

[user@10.0.0.152] Get using ports

Print script? [Y/n] 

[SCRIPT]
CLUSTER:
cluster_add cluster 0:1

GW:
cluster 1 redis1 10.0.0.151 6000
cluster 2 redis2 10.0.0.152 6000

PG:
pg_add cluster 0
pg_add cluster 1
pg_add cluster 2
pg_add cluster 3

PN PG MAP:
slot_set_pg cluster 0:2047 0
slot_set_pg cluster 2048:4095 1
slot_set_pg cluster 4096:6143 2
slot_set_pg cluster 6144:8191 3

PGS:
cluster 0 0 redis1 10.0.0.151 7000
cluster 50 0 redis2 10.0.0.152 7000
cluster 1 1 redis1 10.0.0.151 7010
cluster 51 1 redis2 10.0.0.152 7010
cluster 2 2 redis1 10.0.0.151 7020
cluster 52 2 redis2 10.0.0.152 7020
cluster 3 3 redis1 10.0.0.151 7030
cluster 53 3 redis2 10.0.0.152 7030

Print configuration? [Y/n] 

[GW INFORMATION]
+-------+------------------------------------------+--------+
| GW_ID |                    PM                    |  PORT  |
+-------+------------------------------------------+--------+
|     1 |           ['redis1', '10.0.0.151'] |   6000 |
|     2 |           ['redis2', '10.0.0.152'] |   6000 |
+-------+------------------------------------------+--------+

[PG INFORMATION]
+-------+--------------+-----------+
| PG_ID |     SLOT     | SLOT SIZE |
+-------+--------------+-----------+
|     0 |      0  2047 |      2048 |
|     1 |   2048  4095 |      2048 |
|     2 |   4096  6143 |      2048 |
|     3 |   6144  8191 |      2048 |
+-------+--------------+-----------+

[PGS INFORMATION]
+-------+--------+------------------------------------------+--------+
| PG_ID | PGS_ID |                    PM                    |  PORT  |
+-------+--------+------------------------------------------+--------+
|     0 |      0 |           ['redis1', '10.0.0.151'] |   7000 |
|     0 |     50 |           ['redis2', '10.0.0.152'] |   7000 |
|     1 |      1 |           ['redis1', '10.0.0.151'] |   7010 |
|     1 |     51 |           ['redis2', '10.0.0.152'] |   7010 |
|     2 |      2 |           ['redis1', '10.0.0.151'] |   7020 |
|     2 |     52 |           ['redis2', '10.0.0.152'] |   7020 |
|     3 |      3 |           ['redis1', '10.0.0.151'] |   7030 |
|     3 |     53 |           ['redis2', '10.0.0.152'] |   7030 |
+-------+--------+------------------------------------------+--------+

[PGS INFORMATION, After Arranging locations of masters]
+-------+--------+------------------------------------------+--------+
| PG_ID | PGS_ID |                    PM                    |  PORT  |
+-------+--------+------------------------------------------+--------+
|     0 |      0 |           ['redis1', '10.0.0.151'] |   7000 |
|     0 |     50 |           ['redis2', '10.0.0.152'] |   7000 |
|     1 |     51 |           ['redis2', '10.0.0.152'] |   7010 |
|     2 |      2 |           ['redis1', '10.0.0.151'] |   7020 |
|     2 |     52 |           ['redis2', '10.0.0.152'] |   7020 |
|     3 |     53 |           ['redis2', '10.0.0.152'] |   7030 |
|     1 |      1 |           ['redis1', '10.0.0.151'] |   7010 |
|     3 |      3 |           ['redis1', '10.0.0.151'] |   7030 |
+-------+--------+------------------------------------------+--------+

[MASTER COUNT]
10.0.0.152 : 2
10.0.0.151 : 2

Create PGS, Continue? [Y/n] 
Confirm Mode? [Y/n] 

Warning: PM Add fail. cmd:pm_add redis1 10.0.0.151, ret:{"state":"error","msg":"-ERR required state is 2, but 1"}
# confmaster error

2016/07/12 10:25:43.836 ERR 016 CM Exception occur while handle request. length: 30, message: "pm_add redis1 10.0.0.151"... com.navercorp.nbasearc.confmaster.ConfMasterException$MgmtStateNotSatisfiedException: -ERR required state is 2, but

**Comment by otheng03** [comment]
* Problem 
  * ```{"state":"error","msg":"-ERR required state is 2, but 1"}```
* Solution
  * From 1.3 version of ConfMaster, it is neccesary to send cm_start command to ConfMaster in order to begin ConfMaster service.
  * Follow below steps
    1. Connect to ConfMaster. (I usually use 'telnet')
    2. execute cm_start
    3. cm_info to check state of ConfMaster
  * ex  (must replace ip and port with yours ConfMaster)
  ![image](https://cloud.githubusercontent.com/assets/5895507/16752628/ead2c160-481d-11e6-943e-cc475e51a4c3.png)

Sorry for that is not applied to the manual. If any other problems after you execute cm_start command on it, comment your problem, please.

**Comment by drawhan** [comment]
thank you for your answer

execute cm_start and install is fine... but other error occur

execute batch log
----------------------------------------------------------------------------------------------------------------
[localhost] Check Local Binary
[localhost] local: test -e ~/nbase-arc/bin/redis-arc-v1.3.0-6-gbe31eca
[localhost] local: test -e ~/nbase-arc/bin/cluster-util-v1.3.0-6-gbe31eca
[localhost] local: test -e ~/nbase-arc/bin/redis-gateway-v1.3.0-6-gbe31eca
[localhost] local: test -e ~/nbase-arc/bin/smr-replicator-v1.3.0-6-gbe31eca
[localhost] local: test -e ~/nbase-arc/bin/smr-logutil-v1.3.0-6-gbe31eca
[localhost] Check Local Binary Success

[ttp@localhost] copy_binary begin
[ttp@localhost] Executing task 'copy_binary'
[ttp@localhost] copy_binary end
[ttp@localhost] Executing task 'path_exist'
[ttp@localhost] Executing task 'path_exist'
[ttp@localhost] Executing task 'make_remote_path'
[ttp@localhost] Create directory, ~/nbase-arc/pgs/7020/smr/log. Continue? [Y/n] 




zookeeper log
----------------------------------------------------------------------------------------------------------------
2016/07/12 14:27:48.905 ERR 042 CM -ERR pgs does not exist. cluster_redis/pgs:50
2016/07/12 14:27:48.905 ERR 042 CM Exception occur while handle request. length: 20, message: "pgs_info cluster_redis 50"... java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.navercorp.nbasearc.confmaster.server.mapping.Caller.invoke(Caller.java:49)
	at com.navercorp.nbasearc.confmaster.server.command.CommandTemplate.lock(CommandTemplate.java:209)
	at com.navercorp.nbasearc.confmaster.server.command.CommandTemplate.call(CommandTemplate.java:87)
	at com.navercorp.nbasearc.confmaster.server.command.CommandTemplate.call(CommandTemplate.java:50)
	at com.navercorp.nbasearc.confmaster.context.ExecutionContext.call(ExecutionContext.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: -ERR pgs does not exist. cluster_redis/pgs:50
	at com.navercorp.nbasearc.confmaster.repository.lock.HierarchicalLockPGS.<init>(HierarchicalLockPGS.java:53)
	at com.navercorp.nbasearc.confmaster.repository.lock.HierarchicalLockPG.pgs(HierarchicalLockPG.java:50)
	at com.navercorp.nbasearc.confmaster.server.command.PartitionGroupServerService.pggInfoLock(PartitionGroupServerService.java:351)
	... 14 more

**Comment by otheng03** [comment]
* Exceptions
  * exceptions in 'zookeeper log' section are not critical error, it is just a notice that pgs-50 does not exist. Mgmt script checks if pgs already exist, before installs it.
* additional error
  * If you hare your config files of mgmt script and I can help you.

**Comment by drawhan** [comment]
thanks for your answer

here is my config of mgmt

$vi nbase-arc/mgmt/config/conf_mnode.py

import os

# CM
**CONF_MASTER_IP = "redis1"
CONF_MASTER_PORT = "1122"**
CONF_MASTER_MGMT_CONS = 3

# Local binary path
LOCAL_BINARY_PATH = '~/nbase-arc/bin'

# Migration
MIN_TIME_TO_ATTEMPT_MIG2PC = 0.05   # Minimum time to try mig2pc in second

# Remote
**USERNAME = "user"**

REMOTE_NBASE_ARC = '~/nbase-arc'
REMOTE_BIN_DIR = REMOTE_NBASE_ARC + '/bin'
REMOTE_PGS_DIR = REMOTE_NBASE_ARC + '/pgs'
REMOTE_GW_DIR = REMOTE_NBASE_ARC + '/gw'

# Shell
ARC_BASH_PROFILE = 'bash.nbase-arc'
SHELL = '/bin/bash --rcfile ~/.%s -i -c' % ARC_BASH_PROFILE

**Comment by otheng03** [comment]
* It is recommended to change the value of CONF_MASTER_PORT to a 16-bit integer.
  - CONF_MASTER_PORT = ~~"1122"~~```1122```
* Other configurations in conf_mnode.py seem reasonable. If other configurations are correct mgmt script will work fine.

**Comment by drawhan** [comment]
i found new error when make test after get git file

$git clone https://github.com/naver/nbase-arc.git

$cd nbase-arc

$make test

..............................

cc: error: ../../smr/smr/libsmr.a: No such file or directory
make[2]: *** [redis-server] Error 1
make[2]: Leaving directory `/home/ttp/src/nbase-arc/redis-2.8.8/src'
make[1]: *** [test] Error 2
make[1]: Leaving directory `/home/ttp/src/nbase-arc/redis-2.8.8'
make: *** [test] Error 2


Is it Okay?

**Comment by otheng03** [comment]
@drawhan 
It seems a compilation error therefore it should branch to a new issue #79
