### ISSUE TITLE
compilation error while make test

### ISSUE THREAD

**Issue by otheng03** [naver/nbase-arc#79]
From #77 

@drawhan asked an error about 'make test'

```
cc: error: ../../smr/smr/libsmr.a: No such file or directory
make[2]: *** [redis-server] Error 1
make[2]: Leaving directory /home/ttp/src/nbase-arc/redis-2.8.8/src'
make[1]: *** [test] Error 2
make[1]: Leaving directory/home/ttp/src/nbase-arc/redis-2.8.8'
make: *** [test] Error 2
```

**Comment by otheng03** [comment]
@drawhan
* To perform 'make test'
Why you failed to 'make test' is that you didn't perform 'make gcov' before performing 'make test'.
In error messages, notice ```cc: error: ../../smr/smr/libsmr.a: No such file or directory```.
libsmr.a is created after performing 'make gcov' or 'make'.

* Get recent source code from git
There is some missing test configurations in Makefiles.
We fixed Makefiles so that you had better to get recent source code.

* Whether tests succeed or not depends on your linux and machine environment.

Thank you.

**Comment by Tiaoyu** [comment]
make release Failed
Generating /home/ubuntu/software/nbase-arc/api/java/target/apidocs/help-doc.html...
2 errors
100 warnings
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.758 s
[INFO] Finished at: 2017-07-31T11:55:35+08:00
[INFO] Final Memory: 28M/77M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project nbase-arc-java-client: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/spring/SessionOfHashListOperations.java:322: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/spring/SessionOfHashListOperations.java:323: warning: no description for @param
[ERROR] * @param field
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/spring/SessionOfHashSetOperations.java:323: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/spring/SessionOfHashSetOperations.java:324: warning: no description for @param
[ERROR] * @param field
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/spring/RedisClusterTemplate.java:22: error: malformed HTML
[ERROR] * You must annotate @Qualifier to use this class with <String, String> type of generic,
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/spring/RedisClusterTemplate.java:22: error: bad use of '>'
[ERROR] * You must annotate @Qualifier to use this class with <String, String> type of generic,
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:118: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:119: warning: no description for @param
[ERROR] * @param milliseconds
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:132: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:133: warning: no description for @param
[ERROR] * @param millisecondsTimestamp
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:195: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:221: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:424: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:425: warning: no description for @param
[ERROR] * @param increment
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:426: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:445: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:446: warning: no description for @param
[ERROR] * @param value
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:515: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:516: warning: no description for @param
[ERROR] * @param milliseconds
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:517: warning: no description for @param
[ERROR] * @param value
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:518: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:539: warning: no description for @param
[ERROR] * @param keys
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:559: warning: no description for @param
[ERROR] * @param keysvalues
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:572: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:573: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:585: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:586: warning: no description for @param
[ERROR] * @param start
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:587: warning: no description for @param
[ERROR] * @param end
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:588: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:599: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:600: warning: no description for @param
[ERROR] * @param arguments
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:601: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:685: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:686: warning: no description for @param
[ERROR] * @param field
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:687: warning: no description for @param
[ERROR] * @param increment
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:688: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:1108: warning: no @param for count
[ERROR] List<byte[]> srandmember(byte[] key, int count);
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:1752: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:1764: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:1765: warning: no description for @param
[ERROR] * @param ttl
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/BinaryRedisClusterCommands.java:1766: warning: no description for @param
[ERROR] * @param serializedValue
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:94: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:95: warning: no description for @param
[ERROR] * @param field
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:96: warning: no description for @param
[ERROR] * @param name
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:97: warning: no description for @param
[ERROR] * @param unixTime
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:98: warning: no description for @param
[ERROR] * @param values
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:340: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:341: warning: no description for @param
[ERROR] * @param field
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:342: warning: no description for @param
[ERROR] * @param name
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:343: warning: no description for @param
[ERROR] * @param unixTime
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/TriplesRedisClusterCommands.java:344: warning: no description for @param
[ERROR] * @param values
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:92: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:93: warning: no description for @param
[ERROR] * @param field
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:94: warning: no description for @param
[ERROR] * @param name
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:95: warning: no description for @param
[ERROR] * @param unixTime
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:96: warning: no description for @param
[ERROR] * @param values
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:337: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:338: warning: no description for @param
[ERROR] * @param field
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:339: warning: no description for @param
[ERROR] * @param name
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:340: warning: no description for @param
[ERROR] * @param unixTime
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/triples/BinaryTriplesRedisClusterCommands.java:341: warning: no description for @param
[ERROR] * @param values
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:122: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:123: warning: no description for @param
[ERROR] * @param milliseconds
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:136: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:137: warning: no description for @param
[ERROR] * @param millisecondsTimestamp
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:198: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:224: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:418: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:419: warning: no description for @param
[ERROR] * @param increment
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:420: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:439: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:440: warning: no description for @param
[ERROR] * @param value
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:509: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:510: warning: no description for @param
[ERROR] * @param milliseconds
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:511: warning: no description for @param
[ERROR] * @param value
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:512: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:533: warning: no description for @param
[ERROR] * @param keys
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:553: warning: no description for @param
[ERROR] * @param keysvalues
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:566: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:567: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:579: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:580: warning: no description for @param
[ERROR] * @param start
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:581: warning: no description for @param
[ERROR] * @param end
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:582: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:593: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:594: warning: no description for @param
[ERROR] * @param arguments
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:595: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:679: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:680: warning: no description for @param
[ERROR] * @param field
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:681: warning: no description for @param
[ERROR] * @param increment
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:682: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:1103: warning: no @param for count
[ERROR] List<String> srandmember(String key, int count);
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:1747: warning: no @return
[ERROR] Long dbSize();
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:1760: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:1772: warning: no description for @param
[ERROR] * @param key
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:1773: warning: no description for @param
[ERROR] * @param ttl
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterCommands.java:1774: warning: no description for @param
[ERROR] * @param serializedValue
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterPool.java:98: warning: no @param for keyspace
[ERROR] public RedisClusterPool(final RedisClusterPoolConfig poolConfig, final String host, int port, int timeout,
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterPoolAsync.java:73: warning: no @param for keyspace
[ERROR] public RedisClusterPoolAsync(final RedisClusterPoolConfig poolConfig, final String host, int port, int timeout,
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterPoolAsync.java:73: warning: no @param for gcp
[ERROR] public RedisClusterPoolAsync(final RedisClusterPoolConfig poolConfig, final String host, int port, int timeout,
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterPoolConfig.java:24: warning: empty <p> tag
[ERROR] * <p>
[ERROR] ^
[ERROR] /home/ubuntu/software/nbase-arc/api/java/src/main/java/com/navercorp/redis/cluster/RedisClusterPoolConfig.java:30: warning: empty <p> tag
[ERROR] * <p>
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-8-oracle/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/ubuntu/software/nbase-arc/api/java/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Makefile:2: recipe for target 'all' failed
make[2]: *** [all] Error 1
make[2]: Leaving directory '/home/ubuntu/software/nbase-arc/api/java'
Makefile:6: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/software/nbase-arc/api'
Makefile:12: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by otheng03** [comment]
@Tiaoyu 
This errors are fixed by https://github.com/naver/nbase-arc/commit/eec97c146aa76712c3f752d849dc6eb712714b50 
Please retry to compile. Thank you.
