### ISSUE TITLE
Newer version of redis

### ISSUE THREAD

**Issue by usergoodvery** [naver/nbase-arc#90]
Hi 
If I understood well, your architecture depends on a modified redis version 2.8.8. Are there plans to upgrade your base redis to a more recent version? This hard dependency is quite unfortunate.

**Comment by sanitysoon** [comment]
hi, @usergoodvery 
We are working on Redis 3.2.x for the next release and the release date is expected to be early in next year.

The hard dependency is mainly from our replication mechanism where a user request is executed after replication. We tries to make our Redis modification to be more readable. ^^

**Comment by usergoodvery** [comment]
great thanks for clarifying that. I think ideally, a patch should be published along side the release.

**Comment by usergoodvery** [comment]
Hi,
Are you still planning on releasing an upgraded version of redis?

**Comment by sanitysoon** [comment]
Yes. But release date cannot be confirmed. (sorry)

FYI, 
redis 3.2.x porting is completed and under test. 
Other features we plan to commit before/with redis version-up are not yet implemented.
- Java API enhancement  (async. interface) (nothing to do with version up but.. we need this feature.)
- API handles new data types (such as hyper-log-log data type)
- etc.
